CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(255) NOT NULL
);

INSERT INTO messages (text)
SELECT 'Hello World from RDS!'
WHERE NOT EXISTS (SELECT 1 FROM messages);
